<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>try on FAFA Blog</title>
    <link>https://procarihana.github.io/public/tags/try/</link>
    <description>Recent content in try on FAFA Blog</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>zh-Hans</language>
    <copyright>&lt;a href=&#34;https://creativecommons.org/licenses/by-nc/4.0/&#34; target=&#34;_blank&#34; rel=&#34;noopener&#34;&gt;CC BY-NC 4.0&lt;/a&gt;</copyright>
    <lastBuildDate>Tue, 01 Sep 2020 07:07:27 +0800</lastBuildDate>
    
	<atom:link href="https://procarihana.github.io/public/tags/try/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Try/catch</title>
      <link>https://procarihana.github.io/public/exerciseproblems/catch/</link>
      <pubDate>Tue, 01 Sep 2020 07:07:27 +0800</pubDate>
      
      <guid>https://procarihana.github.io/public/exerciseproblems/catch/</guid>
      <description>Try/catch    try { int i = 10 / 0; } finally { System.out.println(&amp;#34;last&amp;#34;); }  能够成功执行，并且会返回last，同时也会返回Exeception 提示：: / by zero  finally 不一定都会被执行   try里面包含System.exit() finally 里包含异常就会抛出异常并终止执行  try { System.out.println(&amp;#34;try&amp;#34;); } catch (Exception e) { System.out.println(&amp;#34;catch&amp;#34;); } finally { int k = 3 / 0; System.out.println(&amp;#34;finally&amp;#34;); } System.out.println(&amp;#34;main&amp;#34;); </description>
    </item>
    
  </channel>
</rss>